[project]
name = "anyflip-dl"
author = "Ali Karim"
version = "1.1.1"
description = "App to download anyflip books as PDFs"
readme = "README.md"
license = "GPL-3.0-only"
license-files = ["LICENSE"]
requires-python = ">=3.14"
dependencies = [
    "aiofiles>=25.1.0",
    "httpx[http2]>=0.28.1",
    "pillow>=12.1.1",
    "pyside6>=6.10.2",
]

[project.urls]
Repository = "https://github.com/AlimulK/anyflip-dl"
