name: MacOS Build

on:
    push:

jobs:
  pyinstaller-build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ['macos-latest']
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1.6.0
        with:
          python_ver: '3.12'
          pyinstaller_ver: '==6.7.0'
          spec: 'main.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'anyflip-dl-macos'
          options: --onedir, --name "anyflip-dl", --windowed, --icon "pyflip.ico",
